### ISSUE TITLE
OAI generation examples

### ISSUE THREAD

**Issue by JR-1991** [JR-1991/pyDataverse-generation-analysis#1]
Issue to discuss the examples of this repository. See README on `main` for details.

**Comment by JR-1991** [comment]
The usage of `tags` within the OAI specifications could be improved. I have added `native` to all endpoints, but I feel like that this is very broad and less useful due to the amount of endpoints available.

I'd propose adding tags based on the type the endpoint addresses. For instance:

```yaml
/api/v1/files/{identifier}:
    get:
        tags:
            -  files
 /api/v1/datasets/{identifier}:
    get:
        tags:
            -  datasets
```

This would result in a better logical structure and help to organize the OAI doc. In addition, both OAI-Gen and Speakeasy use these tags as module names. Hence, these could be used in the following way:

```python
res = s.datasets.export_dataset(...)

# or

res = s.files.get_file_metadata(...)
```
